# Use the official Go image to build the application
# FROM golang:1.19 as builder
FROM golang:1.19

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project to the container
COPY . .

# Build the Go application inside the container
RUN GOOS=linux GOARCH=amd64 go build -o app .

# # Use a minimal base image to run the application
# FROM alpine:latest

# # Copy the built binary from the builder image to the runtime image
# COPY --from=builder /app/app /app/app

# RUN ls -l /app

# Expose the port that the application listens on
EXPOSE 8080

# Start the application
CMD ["/app/app"]
